version: '3.8'

services:
  postgres:
    container_name: fastyticket-database
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=fastyticket
