version: '3.8'

services:
  # app:
  #   container_name: app-fastyticket
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  db:
    container_name: database-fastyticket
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastyticket
    volumes:
      - ./data/pg:/data/postgres