version: '3.8'

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: fastyticket-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fastyticket-networks

  db:
    container_name: database-fastyticket
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastyticket
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - fastyticket-networks
networks:
  fastyticket-networks: